'use client'

import { useEffect, useState } from 'react'
import { createClient } from '@/lib/supabase/client'
import { useToast } from '@/components/dashboard/Toast'

interface SocialPost {
  id: string
  client_id: string
  platform: string | null
  caption: string | null
  image_url: string | null
  status: string
  scheduled_for: string | null
  published_at: string | null
  rejection_reason: string | null
  source: string | null
  idea_id: string | null
  created_at: string
  updated_at: string | null
}

type StatusFilter = 'all' | 'pending_approval' | 'approved' | 'scheduled' | 'published' | 'rejected'

const STATUS_FILTERS: { key: StatusFilter; label: string }[] = [
  { key: 'all', label: 'All' },
  { key: 'pending_approval', label: 'Pending' },
  { key: 'approved', label: 'Approved' },
  { key: 'scheduled', label: 'Scheduled' },
  { key: 'published', label: 'Published' },
  { key: 'rejected', label: 'Rejected' },
]

function statusBadge(status: string) {
  const map: Record<string, { bg: string; text: string; label: string }> = {
    draft: { bg: 'bg-gray-100', text: 'text-gray-600', label: 'Draft' },
    pending_approval: { bg: 'bg-amber-50', text: 'text-amber-700', label: 'Pending approval' },
    approved: { bg: 'bg-green-50', text: 'text-green-700', label: 'Approved' },
    scheduled: { bg: 'bg-blue-50', text: 'text-blue-700', label: 'Scheduled' },
    published: { bg: 'bg-blue-50', text: 'text-blue-700', label: 'Published' },
    rejected: { bg: 'bg-red-50', text: 'text-red-700', label: 'Rejected' },
  }
  const s = map[status] ?? { bg: 'bg-gray-100', text: 'text-gray-600', label: status }
  return (
    <span className={`inline-flex items-center rounded-full px-2 py-0.5 text-xs font-medium ${s.bg} ${s.text}`}>
      {s.label}
    </span>
  )
}

function platformBadge(platform: string | null) {
  if (!platform) return null
  const p = platform.toLowerCase()
  if (p.includes('facebook') && p.includes('instagram')) {
    return <span className="inline-flex items-center rounded-full bg-purple-50 px-2 py-0.5 text-xs font-medium text-purple-700">Facebook + Instagram</span>
  }
  if (p.includes('instagram')) {
    return <span className="inline-flex items-center rounded-full bg-pink-50 px-2 py-0.5 text-xs font-medium text-pink-700">Instagram</span>
  }
  if (p.includes('facebook')) {
    return <span className="inline-flex items-center rounded-full bg-blue-50 px-2 py-0.5 text-xs font-medium text-blue-700">Facebook</span>
  }
  return <span className="inline-flex items-center rounded-full bg-gray-100 px-2 py-0.5 text-xs font-medium text-gray-600">{platform}</span>
}

function sourceLabel(source: string | null) {
  if (source === 'manus_generated') return 'Generated by Manus'
  if (source === 'client_idea') return 'From your idea'
  if (source === 'manual') return 'Manual'
  return null
}

function formatDate(iso: string | null) {
  if (!iso) return null
  const d = new Date(iso)
  return d.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric', hour: 'numeric', minute: '2-digit' })
}

export default function ContentQueue({ clientId }: { clientId: string }) {
  const supabase = createClient()
  const { showToast } = useToast()
  const [posts, setPosts] = useState<SocialPost[]>([])
  const [loading, setLoading] = useState(true)
  const [filter, setFilter] = useState<StatusFilter>('all')
  const [rejectingId, setRejectingId] = useState<string | null>(null)
  const [rejectReason, setRejectReason] = useState('')
  const [submitting, setSubmitting] = useState<string | null>(null)

  useEffect(() => {
    async function load() {
      setLoading(true)
      let query = supabase
        .from('social_posts')
        .select('*')
        .eq('client_id', clientId)
        .order('created_at', { ascending: false })

      if (filter !== 'all') {
        query = query.eq('status', filter)
      }

      const { data, error } = await query
      if (error) {
        showToast('Failed to load posts', 'error')
      }
      setPosts(data ?? [])
      setLoading(false)
    }
    load()
  }, [clientId, filter])

  // Count posts by status for filter pills
  const [counts, setCounts] = useState<Record<string, number>>({})
  useEffect(() => {
    async function loadCounts() {
      const { data } = await supabase
        .from('social_posts')
        .select('status')
        .eq('client_id', clientId)
      if (data) {
        const c: Record<string, number> = { all: data.length }
        for (const row of data) {
          c[row.status] = (c[row.status] ?? 0) + 1
        }
        setCounts(c)
      }
    }
    loadCounts()
  }, [clientId, posts])

  async function handleApprove(postId: string) {
    setSubmitting(postId)
    const { error } = await supabase
      .from('social_posts')
      .update({ status: 'approved', updated_at: new Date().toISOString() })
      .eq('id', postId)

    if (error) {
      showToast('Failed to approve post', 'error')
    } else {
      setPosts((prev) => prev.map((p) => (p.id === postId ? { ...p, status: 'approved' } : p)))
      showToast('Post approved', 'success')
    }
    setSubmitting(null)
  }

  async function handleReject(postId: string) {
    if (!rejectReason.trim()) return
    setSubmitting(postId)
    const { error } = await supabase
      .from('social_posts')
      .update({
        status: 'rejected',
        rejection_reason: rejectReason.trim(),
        updated_at: new Date().toISOString(),
      })
      .eq('id', postId)

    if (error) {
      showToast('Failed to reject post', 'error')
    } else {
      setPosts((prev) =>
        prev.map((p) =>
          p.id === postId ? { ...p, status: 'rejected', rejection_reason: rejectReason.trim() } : p
        )
      )
      showToast('Post rejected', 'success')
      setRejectingId(null)
      setRejectReason('')
    }
    setSubmitting(null)
  }

  const isResolved = (status: string) => ['approved', 'rejected', 'published', 'scheduled'].includes(status)

  if (loading) {
    return (
      <div className="rounded-xl border border-gray-200 bg-white p-12 text-center">
        <p className="text-sm text-gray-500">Loading posts...</p>
      </div>
    )
  }

  return (
    <div className="space-y-6">
      {/* Filter pills */}
      <div className="flex flex-wrap gap-2">
        {STATUS_FILTERS.map((f) => {
          const count = counts[f.key] ?? 0
          const active = filter === f.key
          return (
            <button
              key={f.key}
              onClick={() => setFilter(f.key)}
              className={`rounded-full px-3 py-1.5 text-xs font-medium transition-colors ${
                active
                  ? 'bg-gray-900 text-white'
                  : 'bg-white border border-gray-200 text-gray-600 hover:bg-gray-50'
              }`}
            >
              {f.label} ({count})
            </button>
          )
        })}
      </div>

      {/* Posts */}
      {posts.length === 0 ? (
        <div className="rounded-xl border border-gray-200 bg-white p-12 text-center">
          <div className="mx-auto mb-3 flex h-12 w-12 items-center justify-center rounded-full bg-gray-100">
            <svg className="h-6 w-6 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M19.5 14.25v-2.625a3.375 3.375 0 0 0-3.375-3.375h-1.5A1.125 1.125 0 0 1 13.5 7.125v-1.5a3.375 3.375 0 0 0-3.375-3.375H8.25m0 12.75h7.5m-7.5 3H12M10.5 2.25H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 0 0-9-9Z" />
            </svg>
          </div>
          <h3 className="text-sm font-semibold text-gray-900 mb-1">No posts yet</h3>
          <p className="text-sm text-gray-500 max-w-sm mx-auto">
            Once your social media manager starts creating content, it&apos;ll show up here for your review.
          </p>
        </div>
      ) : (
        <div className="space-y-4">
          {posts.map((post) => (
            <div
              key={post.id}
              className={`bg-white rounded-[14px] border border-[#e5e7eb] p-5 shadow-[0_1px_3px_rgba(0,0,0,0.04)] transition-opacity ${
                isResolved(post.status) ? 'opacity-65' : ''
              }`}
            >
              {/* Header row: badges */}
              <div className="flex flex-wrap items-center gap-2 mb-3">
                {statusBadge(post.status)}
                {platformBadge(post.platform)}
                {sourceLabel(post.source) && (
                  <span className="text-xs text-gray-400">{sourceLabel(post.source)}</span>
                )}
              </div>

              {/* Content */}
              <div className="flex gap-4">
                <div className="flex-1 min-w-0">
                  {post.caption && (
                    <p className="text-sm text-gray-800 whitespace-pre-wrap leading-relaxed">{post.caption}</p>
                  )}
                  {post.scheduled_for && (
                    <p className="text-xs text-gray-400 mt-2">
                      Scheduled: {formatDate(post.scheduled_for)}
                    </p>
                  )}
                </div>
                {post.image_url && (
                  <img
                    src={post.image_url}
                    alt=""
                    className="w-20 h-20 rounded-lg object-cover flex-shrink-0 border border-gray-100"
                  />
                )}
              </div>

              {/* Rejection reason */}
              {post.status === 'rejected' && post.rejection_reason && (
                <div className="mt-3 rounded-lg bg-red-50 px-3 py-2">
                  <p className="text-xs text-red-600">
                    <span className="font-medium">Rejection reason:</span> {post.rejection_reason}
                  </p>
                </div>
              )}

              {/* Approve / Reject buttons (only for pending) */}
              {post.status === 'pending_approval' && (
                <div className="mt-4 space-y-3">
                  <div className="flex gap-2">
                    <button
                      onClick={() => handleApprove(post.id)}
                      disabled={submitting === post.id}
                      className="rounded-lg bg-green-600 px-4 py-2 text-sm font-medium text-white hover:bg-green-700 transition-colors disabled:opacity-50"
                    >
                      {submitting === post.id ? 'Approving...' : 'Approve'}
                    </button>
                    <button
                      onClick={() => {
                        if (rejectingId === post.id) {
                          setRejectingId(null)
                          setRejectReason('')
                        } else {
                          setRejectingId(post.id)
                          setRejectReason('')
                        }
                      }}
                      disabled={submitting === post.id}
                      className="rounded-lg border border-gray-200 px-4 py-2 text-sm font-medium text-gray-600 hover:border-red-300 hover:text-red-600 hover:bg-red-50 transition-colors disabled:opacity-50"
                    >
                      Reject
                    </button>
                  </div>

                  {/* Reject reason textarea (slides open) */}
                  <div
                    className="overflow-hidden transition-all duration-300 ease-in-out"
                    style={{
                      maxHeight: rejectingId === post.id ? '200px' : '0px',
                      opacity: rejectingId === post.id ? 1 : 0,
                    }}
                  >
                    <div className="rounded-lg border border-gray-200 bg-gray-50 p-3 space-y-2">
                      <textarea
                        value={rejectReason}
                        onChange={(e) => setRejectReason(e.target.value)}
                        placeholder="What didn't you like about this post?"
                        rows={2}
                        className="w-full rounded-md border border-gray-300 px-3 py-2 text-sm focus:border-red-400 focus:outline-none focus:ring-1 focus:ring-red-400 resize-none"
                      />
                      <button
                        onClick={() => handleReject(post.id)}
                        disabled={!rejectReason.trim() || submitting === post.id}
                        className="rounded-lg bg-red-600 px-4 py-1.5 text-sm font-medium text-white hover:bg-red-700 transition-colors disabled:opacity-50"
                      >
                        {submitting === post.id ? 'Submitting...' : 'Submit rejection'}
                      </button>
                    </div>
                  </div>
                </div>
              )}
            </div>
          ))}
        </div>
      )}
    </div>
  )
}
